job_project/admin_app/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

job_project/job_project/urls.py
from django.conf.urls import url, include
#from django.contrib import admin

urlpatterns = [
    url(r'^', include('jobpost_app.urls', namespace='jobpost_app')),
    url(r'^employer/', include('employer_app.urls', namespace='employer_app')),
    url(r'^seeker/', include('jobseeker_app.urls', namespace='seeker_app')),
    #url(r'^admin/', include('admin_app.urls')),
]

job_project/jobpost_app/urls.py
from django.conf.urls import include, url
from jobpost_app.views.index_view import (index_view)
from jobpost_app.views.backend_index_view import (backend_index_view)
from jobpost_app.views.backend_category_view import (backend_category_view, CategoryCrud)
from jobpost_app.views.backend_industry_view import (backend_industry_view, IndustryCrud)
from jobpost_app.views.backend_location_view import (backend_location_view, LocationCrud)

urlpatterns = [
	#Frontend Part
    url(r'^$', index_view, name='index'),
	
	#Backend Part
	url(r'^admin/dashboard/$', backend_index_view, name='backend_index'),
	url(r'^admin/category/$', backend_category_view, name='cat-list'),
	url(r'^admin/category-form/(?P<cat_id>[0-9]*)$', CategoryCrud.as_view(), name='cat-form'),
	url(r'^admin/industry/$', backend_industry_view, name='ind-list'),
	url(r'^admin/industry-form/(?P<ind_id>[0-9]*)$', IndustryCrud.as_view(), name='ind-form'),
	url(r'^admin/location/$', backend_location_view, name='job-loc'),
	url(r'^admin/location-form/(?P<loc_id>[0-9]*)$', LocationCrud.as_view(), name='loc-form'),
]

job_project/jobpost_app/models/category.py
from django.db import models

# Create your models here.
class Category(models.Model):
  name = models.CharField(max_length=200, default="")
  slug = models.CharField(max_length=250, default="", unique=True)
  description = models.CharField(max_length=400, default="")
  create_by = models.CharField(max_length=20, default="")
  create_date = models.DateTimeField(auto_now_add=True, null=True)
  update_by = models.CharField(max_length=20, default="")
  update_date = models.DateTimeField(auto_now=True, null=True)
  active = models.BooleanField(default=True)

job_project/jobpost_app/models/industry.py
from django.db import models

# Create your models here.
class Industry(models.Model):
  name = models.CharField(max_length=200, default="")
  slug = models.CharField(max_length=250, default="", unique=True)
  description = models.CharField(max_length=400, default="")
  create_by = models.CharField(max_length=20, default="")
  create_date = models.DateTimeField(auto_now_add=True, null=True)
  update_by = models.CharField(max_length=20, default="")
  update_date = models.DateTimeField(auto_now=True, null=True)
  active = models.BooleanField(default=True)

job_project/jobpost_app/models/location.py
from django.db import models

# Create your models here.
class Location(models.Model):
  name = models.CharField(max_length=200, default="")
  slug = models.CharField(max_length=250, default="", unique=True)
  description = models.CharField(max_length=400, default="")
  create_by = models.CharField(max_length=20, default="")
  create_date = models.DateTimeField(auto_now_add=True, null=True)
  update_by = models.CharField(max_length=20, default="")
  update_date = models.DateTimeField(auto_now=True, null=True)
  active = models.BooleanField(default=True)

job_project/jobpost_app/views/backend_category_view.py
from django.shortcuts import render
from jobpost_app.models import Category
from django.views import View


# Create your views here.
def backend_category_view(request):
  template="jobpost_app/backend/category_list.html"
  cats=Category.objects.filter(active=True)
  context={'title':'Category List', 'cats':cats}
  return render(request, template, context)

class CategoryCrud(View):
  template="jobpost_app/backend/category_form.html"
  
  def get(self, request, cat_id=None):
    if cat_id:
      cat=Category.objects.get(pk=cat_id)
      context={'title':'Category Form', 'cat':cat}
      return render(request, self.template, context)
    else:
      return render(request, self.template, {'title':'Category Form'})
	
  def post(self, request, cat_id=None):
    name=request.POST.get('name','')
    slug=request.POST.get('slug','')
    desc=request.POST.get('description','')
    #status=request.POST.get('status','')
	
    if cat_id:
      cat=Category.objects.get(pk=cat_id)
      cat.name=name
      cat.slug=slug.lower()
      cat.description=desc
      #cat.active=status
      cat.save()
      msg='Data Updated Successfully'
    else:
      cat = Category(
        name = name,
        slug = slug.lower(),
        description = desc
        #active = status	  
	  )
      cat.save()
      msg='Data Inserted Successfully'
    context={'title':'Category Form', 'cat':cat, 'msg':msg}
    return render(request, self.template, context)

job_project/jobpost_app/views/backend_index_view.py
from django.shortcuts import render
from jobpost_app.models import Location


# Create your views here.
def backend_index_view(request):
  template="jobpost_app/backend/index.html"
  context={'title':'Jobpost Admin'}
  return render(request, template, context)

job_project/jobpost_app/views/backend_industry_view.py
from django.shortcuts import render
from jobpost_app.models import Industry
from django.views import View


# Create your views here.
def backend_industry_view(request):
  template="jobpost_app/backend/industry_list.html"
  inds=Industry.objects.filter(active=True)
  context={'title':'Industry List', 'inds':inds}
  return render(request, template, context)

class IndustryCrud(View):
  template="jobpost_app/backend/industry_form.html"
  
  def get(self, request, ind_id=None):
    if ind_id:
      ind=Industry.objects.get(pk=ind_id)
      context={'title':'Industry Form', 'ind':ind}
      return render(request, self.template, context)
    else:
      return render(request, self.template, {'title':'Industry Form'})
	
  def post(self, request, ind_id=None):
    name=request.POST.get('name','')
    slug=request.POST.get('slug','')
    desc=request.POST.get('description','')
    #status=request.POST.get('status','')
	
    if ind_id:
      ind=Industry.objects.get(pk=ind_id)
      ind.name=name
      ind.slug=slug.lower()
      ind.description=desc
      #ind.active=status
      ind.save()
      msg='Data Updated Successfully'
    else:
      ind = Industry(
        name = name,
        slug = slug.lower(),
        description = desc
        #active = status	  
	  )
      ind.save()
      msg='Data Inserted Successfully'
    context={'ind':ind, 'msg':msg}
    return render(request, self.template, context)

job_project/jobpost_app/views/backend_location_view.py
from django.shortcuts import render
from jobpost_app.models import Location
from django.views import View


# Create your views here.
def backend_location_view(request):
  template="jobpost_app/backend/location_list.html"
  locations=Location.objects.filter(active=True)
  context={'title':'Job Location List','locs':locations}
  return render(request, template, context)

  
class LocationCrud(View):
  template="jobpost_app/backend/location_form.html"
  
  def get(self, request, loc_id=None):
    if loc_id:
      loc=Location.objects.get(pk=loc_id)
      context={'title':'Job Location Form', 'loc':loc}
      return render(request, self.template, context)
    else:
      return render(request, self.template, {'title':'Job Location Form'})
	
  def post(self, request, loc_id=None):
    name=request.POST.get('name','')
    slug=request.POST.get('slug','')
    desc=request.POST.get('description','')
    #status=request.POST.get('status','')
	
    if loc_id:
      loc=Location.objects.get(pk=loc_id)
      loc.name=name
      loc.slug=slug.lower()
      loc.description=desc
      #loc.active=status
      loc.save()
      msg='Data Updated Successfully'
    else:
      loc = Location(
        name = name,
        slug = slug.lower(),
        description = desc
        #active = status	  
	  )
      loc.save()
      msg='Data Inserted Successfully'
    context={'title':'Job Location Form', 'loc':loc, 'msg':msg}
    return render(request, self.template, context)

job_project/jobpost_app/views/index_view.py
from django.shortcuts import render
from jobpost_app.models import Location, Category
#from django.http import HttpResponse


# Create your views here.
def index_view(request):
  template="jobpost_app/frontend/index.html"
  locs=Location.objects.all()
  cats=Category.objects.all()
  context={'title':'Welcome To My Jobs Site', 'locs':locs, 'cats':cats}
  return render(request, template, context)

job_project/jobpost_app/templates/jobpost_app/backend/category_form.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title"><span>{{msg}}</span></h3>
		  <span class="pull-right"><a href="{% url 'jobpost_app:cat-form' '' %}" class="btn btn-primary btn-sm" role="button">Add New</a></span>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="POST" action="{% url 'jobpost_app:cat-form' cat.id %}">
		{% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              <label for="" class="col-md-2 control-label">Category Name</label>
              <div class="col-md-8">
                <input type="text" name="name" value="{{cat.name}}" class="form-control" placeholder="Category Name">
              </div>
            </div>
            
            <div class="form-group">
              <label for="" class="col-md-2 control-label">Category Slug (Unique)</label>
              <div class="col-md-8">
                <input type="text" name="slug" value="{{cat.slug}}" class="form-control" placeholder="Category Slug">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-2 control-label">Description</label>
              <div class="col-md-8">
                <input type="text" name="description" value="{{cat.description}}"  class="form-control" placeholder="Description">
              </div>
            </div>

			<div class="form-group">
			  <div class="col-sm-offset-2 col-md-8">
				<div class="checkbox">
				  <label>
					<input type="checkbox" name="status"> Is Active?
				  </label>
				</div>
			  </div>
			</div>
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <a href="{% url 'jobpost_app:cat-list' %}" class="btn btn-default">Back</a>
            <button type="submit" class="btn btn-info pull-right">Submit</button>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
  </div>
</div>
{% endblock content %}

job_project/jobpost_app/templates/jobpost_app/backend/category_list.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">{{report_title}}</h3>
				<span class="pull-right"><a href="{% url 'jobpost_app:cat-form' '' %}" class="btn btn-primary btn-sm" role="button">Add New</a></span>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<table class="table table-bordered">
					<tbody>
						<tr>
							<th style="width: 10px">SL</th>
							<th>Name</th>
							<th>Description</th>
							<th>Status</th>
							<th>Create By</th>
							<th>Create Date</th>
							<th style="width:120px;text-align:center;">Action</th>
						</tr>
						{% for cat in cats %}
						<tr>
							<td>{{forloop.counter}}.</td>
							<td>{{cat.name}}</td>
							<td>{{cat.description}}</td>
							<td>{{cat.active}}</td>
							<td>{{cat.create_by}}</td>
							<td>{{cat.create_date}}</td>
							<td align="center">
								<div class="btn-group">
									<a href="{% url 'jobpost_app:cat-form' cat.id %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-edit"></i></a>
									<a href="#" class="btn btn-danger btn-sm" role="button"><i class="fa fa-trash"></i></a>
								</div>
							</td>

						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<!-- /.box-body -->
			<div class="box-footer clearfix">
				<ul class="pagination pagination-sm no-margin pull-right">
					<li><a href="#">«</a></li>
					<li><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">»</a></li>
				</ul>
			</div>
		</div>
	  <!-- /.box -->
	</div>
</div>
{% endblock content %}

job_project/jobpost_app/templates/jobpost_app/backend/index.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
      <div class="row">
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-aqua">
            <div class="inner">
              <h3>150</h3>

              <p>Total Jobs Post</p>
            </div>
            <div class="icon">
              <i class="ion ion-bag"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-yellow">
            <div class="inner">
              <h3>44</h3>

              <p>Total Organizations</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-red">
            <div class="inner">
              <h3>65</h3>

              <p>Total Job Seekers</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <!-- ./col -->

        <div class="col-lg-3 col-xs-6">
          <!-- small box -->
          <div class="small-box bg-green">
            <div class="inner">
              <h3>53<sup style="font-size: 20px">%</sup></h3>

              <p>Bounce Rate</p>
            </div>
            <div class="icon">
              <i class="ion ion-stats-bars"></i>
            </div>
            <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
          </div>
        </div>
      </div>

      <!-- Latest Member -->
          <div class="row">
            <div class="col-md-6">
              <!-- USERS LIST -->
              <div class="box box-danger">
                <div class="box-header with-border">
                  <h3 class="box-title">Latest Job Seeker</h3>

                  <div class="box-tools pull-right">
                    <span class="label label-danger">8 New Members</span>
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body no-padding">
                  <ul class="users-list clearfix">
                    <li>
                      <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">Alexander Pierce</a>
                      <span class="users-list-date">Today</span>
                    </li>
                    <li>
                      <img src="{% static 'dist/img/user8-128x128.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">Norman</a>
                      <span class="users-list-date">Yesterday</span>
                    </li>
                    <li>
                      <img src="{% static 'dist/img/user7-128x128.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">Jane</a>
                      <span class="users-list-date">12 Jan</span>
                    </li>
                    <li>
                      <img src="{% static 'dist/img/user6-128x128.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">John</a>
                      <span class="users-list-date">12 Jan</span>
                    </li>
                    <li>
                      <img src="{% static 'dist/img/user2-160x160.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">Alexander</a>
                      <span class="users-list-date">13 Jan</span>
                    </li>
                    <li>
                      <img src="{% static 'dist/img/user5-128x128.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">Sarah</a>
                      <span class="users-list-date">14 Jan</span>
                    </li>
                    <li>
                      <img src="{% static 'dist/img/user4-128x128.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">Nora</a>
                      <span class="users-list-date">15 Jan</span>
                    </li>
                    <li>
                      <img src="{% static 'dist/img/user3-128x128.jpg' %}" alt="User Image">
                      <a class="users-list-name" href="#">Nadia</a>
                      <span class="users-list-date">15 Jan</span>
                    </li>
                  </ul>
                  <!-- /.users-list -->
                </div>
                <!-- /.box-body -->
                <div class="box-footer text-center">
                  <a href="javascript:void(0)" class="uppercase">View All Users</a>
                </div>
                <!-- /.box-footer -->
              </div>
              <!--/.box -->
            </div>

            <div class="col-md-6">
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">Recently Jobs Post</h3>

                  <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  <ul class="products-list product-list-in-box">
                    <li class="item">
                      <div class="product-img">
                        <img src="{% static 'dist/img/default-50x50.gif' %}" alt="Product Image">
                      </div>
                      <div class="product-info">
                        <a href="javascript:void(0)" class="product-title">Logic Coder
                          <span class="label label-warning pull-right">05</span></a>
                        <span class="product-description">
                              Software Quality Assurance Engineer
                            </span>
                      </div>
                    </li>
                    <!-- /.item -->
                    <li class="item">
                      <div class="product-img">
                        <img src="{% static 'dist/img/default-50x50.gif' %}" alt="Product Image">
                      </div>
                      <div class="product-info">
                        <a href="javascript:void(0)" class="product-title">DB Dolphin
                          <span class="label label-success pull-right">02</span></a>
                        <span class="product-description">
                              Tele Marketing Executive (Female)
                            </span>
                      </div>
                    </li>
                    <!-- /.item -->
                    <li class="item">
                      <div class="product-img">
                        <img src="{% static 'dist/img/default-50x50.gif' %}" alt="Product Image">
                      </div>
                      <div class="product-info">
                        <a href="javascript:void(0)" class="product-title">Software Developer
                          <span class="label label-success pull-right">01</span></a>
                        <span class="product-description">
                              DataSoft Systems Bangladesh Limited
                            </span>
                      </div>
                    </li>
                    <!-- /.item -->
                    <li class="item">
                      <div class="product-img">
                        <img src="{% static 'dist/img/default-50x50.gif' %}" alt="Product Image">
                      </div>
                      <div class="product-info">
                        <a href="javascript:void(0)" class="product-title">Technical Lead, Deputy Manager
                          <span class="label label-success pull-right">01</span></a>
                        <span class="product-description">
                              Leading ISP & Data Connectivity Solution Provider
                            </span>
                      </div>
                    </li>
                    <!-- /.item -->
                    <li class="item">
                      <div class="product-img">
                        <img src="{% static 'dist/img/default-50x50.gif' %}" alt="Product Image">
                      </div>
                      <div class="product-info">
                        <a href="javascript:void(0)" class="product-title">Square InformatiX Limited
                          <span class="label label-success pull-right">01</span></a>
                        <span class="product-description">
                              System Administrator
                            </span>
                      </div>
                    </li>
                    <!-- /.item -->
                  </ul>
                </div>
                <!-- /.box-body -->
                <div class="box-footer text-center">
                  <a href="javascript:void(0)" class="uppercase">View All Products</a>
                </div>
                <!-- /.box-footer -->
              </div>
            </div>
          </div>
{% endblock content %}

job_project/jobpost_app/templates/jobpost_app/backend/industry_form.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title"><span>{{msg}}</span></h3>
		  <span class="pull-right"><a href="{% url 'jobpost_app:ind-form' '' %}" class="btn btn-primary btn-sm" role="button">Add New</a></span>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="POST" action="{% url 'jobpost_app:ind-form' ind.id %}">
		{% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              <label for="" class="col-md-2 control-label">Industry Name</label>
              <div class="col-md-8">
                <input type="text" name="name" value="{{ind.name}}" class="form-control" placeholder="Industry Name">
              </div>
            </div>
            
            <div class="form-group">
              <label for="" class="col-md-2 control-label">Industry Slug (Unique)</label>
              <div class="col-md-8">
                <input type="text" name="slug" value="{{ind.slug}}" class="form-control" placeholder="Industry Slug">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-2 control-label">Description</label>
              <div class="col-md-8">
                <input type="text" name="description" value="{{ind.description}}"  class="form-control" placeholder="Description">
              </div>
            </div>

			<div class="form-group">
			  <div class="col-sm-offset-2 col-md-8">
				<div class="checkbox">
				  <label>
					<input type="checkbox" name="status"> Is Active?
				  </label>
				</div>
			  </div>
			</div>
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <a href="{% url 'jobpost_app:ind-list' %}" class="btn btn-default">Back</a>
            <button type="submit" class="btn btn-info pull-right">Submit</button>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
  </div>
</div>
{% endblock content %}

job_project/jobpost_app/templates/jobpost_app/backend/industry_list.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">{{report_title}}</h3>
				<span class="pull-right"><a href="{% url 'jobpost_app:ind-form' '' %}" class="btn btn-primary btn-sm" role="button">Add New</a></span>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<table class="table table-bordered">
					<tbody>
						<tr>
							<th style="width: 10px">SL</th>
							<th>Name</th>
							<th>Description</th>
							<th>Status</th>
							<th>Create By</th>
							<th>Create Date</th>
							<th style="width:120px;text-align:center;">Action</th>
						</tr>
						{% for ind in inds %}
						<tr>
							<td>{{forloop.counter}}.</td>
							<td>{{ind.name}}</td>
							<td>{{ind.description}}</td>
							<td>{{ind.active}}</td>
							<td>{{ind.create_by}}</td>
							<td>{{ind.create_date}}</td>
							<td align="center">
								<div class="btn-group">
									<a href="{% url 'jobpost_app:ind-form' ind.id %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-edit"></i></a>
									<a href="#" class="btn btn-danger btn-sm" role="button"><i class="fa fa-trash"></i></a>
								</div>
							</td>

						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<!-- /.box-body -->
			<div class="box-footer clearfix">
				<ul class="pagination pagination-sm no-margin pull-right">
					<li><a href="#">«</a></li>
					<li><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">»</a></li>
				</ul>
			</div>
		</div>
	  <!-- /.box -->
	</div>
</div>
{% endblock content %}

job_project/jobpost_app/templates/jobpost_app/backend/location_form.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title"><span>{{msg}}</span></h3>
		  <span class="pull-right"><a href="{% url 'jobpost_app:loc-form' '' %}" class="btn btn-primary btn-sm" role="button">Add New</a></span>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="POST" action="{% url 'jobpost_app:loc-form' loc.id %}">
		{% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              <label for="" class="col-md-2 control-label">Location Name</label>
              <div class="col-md-8">
                <input type="text" name="name" value="{{loc.name}}" class="form-control" placeholder="Location Name">
              </div>
            </div>
            
            <div class="form-group">
              <label for="" class="col-md-2 control-label">Location Slug (Unique)</label>
              <div class="col-md-8">
                <input type="text" name="slug" value="{{loc.slug}}" class="form-control" placeholder="Location Slug">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-2 control-label">Description</label>
              <div class="col-md-8">
                <input type="text" name="description" value="{{loc.description}}"  class="form-control" placeholder="Description">
              </div>
            </div>

			<div class="form-group">
			  <div class="col-sm-offset-2 col-md-8">
				<div class="checkbox">
				  <label>
					<input type="checkbox" name="status"> Is Active?
				  </label>
				</div>
			  </div>
			</div>
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <a href="{% url 'jobpost_app:job-loc' %}" class="btn btn-default">Back</a>
            <button type="submit" class="btn btn-info pull-right">Submit</button>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
  </div>
</div>
{% endblock content %}

job_project/jobpost_app/templates/jobpost_app/backend/location_list.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header with-border">
				<h3 class="box-title">{{report_title}}</h3>
				<span class="pull-right"><a href="{% url 'jobpost_app:loc-form' '' %}" class="btn btn-primary btn-sm" role="button">Add New</a></span>
			</div>
			<!-- /.box-header -->
			<div class="box-body">
				<table class="table table-bordered">
					<tbody>
						<tr>
							<th style="width: 10px">SL</th>
							<th>Name</th>
							<th>Description</th>
							<th>Status</th>
							<th>Create By</th>
							<th>Create Date</th>
							<th style="width:120px;text-align:center;">Action</th>
						</tr>
						{% for loc in locs %}
						<tr>
							<td>{{forloop.counter}}.</td>
							<td>{{loc.name}}</td>
							<td>{{loc.description}}</td>
							<td>{{loc.active}}</td>
							<td>{{loc.create_by}}</td>
							<td>{{loc.create_date}}</td>
							<td align="center">
								<div class="btn-group">
									<a href="{% url 'jobpost_app:loc-form' loc.id %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-edit"></i></a>
									<a href="#" class="btn btn-danger btn-sm" role="button"><i class="fa fa-trash"></i></a>
								</div>
							</td>

						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<!-- /.box-body -->
			<div class="box-footer clearfix">
				<ul class="pagination pagination-sm no-margin pull-right">
					<li><a href="#">«</a></li>
					<li><a href="#">1</a></li>
					<li><a href="#">2</a></li>
					<li><a href="#">3</a></li>
					<li><a href="#">»</a></li>
				</ul>
			</div>
		</div>
	  <!-- /.box -->
	</div>
</div>
{% endblock content %}