job_project/admin_app/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

job_project/job_project/urls.py
from django.conf.urls import url, include
#from django.contrib import admin

urlpatterns = [
    url(r'^', include('jobpost_app.urls', namespace='jobpost_app')),
    url(r'^employer/', include('employer_app.urls', namespace='employer_app')),
    url(r'^seeker/', include('jobseeker_app.urls', namespace='seeker_app')),
    #url(r'^admin/', include('admin_app.urls')),
]

job_project/jobpost_app/urls.py
from django.conf.urls import include, url
from jobpost_app.views.index_view import (index_view)
from jobpost_app.views.backend_index_view import (backend_index_view)
from jobpost_app.views.backend_category_view import (backend_category_view, CategoryCrud)
from jobpost_app.views.backend_industry_view import (backend_industry_view, IndustryCrud)
from jobpost_app.views.backend_location_view import (backend_location_view, LocationCrud)

urlpatterns = [
	#Frontend Part
    url(r'^$', index_view, name='index'),
	
	#Backend Part
	url(r'^admin/dashboard/$', backend_index_view, name='backend_index'),
	url(r'^admin/category/$', backend_category_view, name='cat-list'),
	url(r'^admin/category-form/(?P<cat_id>[0-9]*)$', CategoryCrud.as_view(), name='cat-form'),
	url(r'^admin/industry/$', backend_industry_view, name='ind-list'),
	url(r'^admin/industry-form/(?P<ind_id>[0-9]*)$', IndustryCrud.as_view(), name='ind-form'),
	url(r'^admin/location/$', backend_location_view, name='job-loc'),
	url(r'^admin/location-form/(?P<loc_id>[0-9]*)$', LocationCrud.as_view(), name='loc-form'),
]

job_project/templates_app/models.py
from django.db import models

# Create your models here.

job_project/templates_app/views.py
from django.shortcuts import render

# Create your views here.

job_project/templates_app/templates/templates_app/backend/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Jobs Admin Panel</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{% static 'backend/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'backend/bower_components/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'backend/bower_components/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'backend/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect. -->
  <link rel="stylesheet" href="{% static 'backend/dist/css/skins/skin-blue.min.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="{% url 'jobpost_app:backend_index' %}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">Jobs Admin Panel</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Jobs Admin Panel</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          
          <!-- /.messages-menu -->

          <!-- Notifications Menu -->
          
          <!-- Tasks Menu -->
          
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-right">
                  <a href="#" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->

        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->

      <!-- search form (Optional) -->

      <!-- /.search form -->

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Quick Access</li>
        <!-- Optionally, you can add icons to the links -->
		<li class="active">
			<a href="{% url 'jobpost_app:backend_index' %}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a>
		</li>
		<li>
			<a href="{% url 'jobpost_app:cat-list' %}"><i class="fa fa-list-alt"></i> <span>Jobs Category</span></a>
		</li>
        <li>
			<a href="{% url 'jobpost_app:ind-list' %}"><i class="fa fa-industry"></i> <span>Jobs Industry</span></a>
		</li>
        <li><a href="{% url 'jobpost_app:job-loc' %}"><i class="fa fa-location-arrow"></i> <span>Locations</span></a></li>
        <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
              </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#">Link in level 2</a></li>
            <li><a href="#">Link in level 2</a></li>
          </ul>
        </li>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {{ title }}
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
      </ol>
    </section>
    
    <!-- Main content -->
    <section class="content container-fluid">

      <!--------------------------
        | Your Page Content Here |
        -------------------------->
        {% block content %} {% endblock content %}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
  immediately after the control sidebar -->

</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 3 -->
<script src="{% static 'backend/bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'backend/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'backend/dist/js/adminlte.min.js' %}"></script>

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. -->
</body>
</html>