job_project/admin_app/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

job_project/employer_app/urls.py
from django.conf.urls import include, url
from employer_app.views.index_view import index_view
from employer_app.views.employer_view import EmployerCrud, EmployerLoginReg
from employer_app.views.job_post_view import JobPostCrud





urlpatterns = [
    url(r'^dashboard/$', index_view, name='dashboard'),
    url(r'^login/$', EmployerLoginReg.as_view(), name='emp-login'),
	url(r'^update-profile/(?P<emp_id>[0-9]*)$', EmployerCrud.as_view(), name='upd-profile'),
	url(r'^job-post/(?P<job_id>[0-9]*)$', JobPostCrud.as_view(), name='job-post'),
]

job_project/job_project/urls.py
from django.conf.urls import url, include
#from django.contrib import admin

urlpatterns = [
    url(r'^', include('jobpost_app.urls', namespace='jobpost_app')),
    url(r'^employer/', include('employer_app.urls', namespace='employer_app')),
    url(r'^seeker/', include('jobseeker_app.urls', namespace='seeker_app')),
    #url(r'^admin/', include('admin_app.urls')),
]

job_project/employer_app/models/employer.py
from django.db import models


# Create your models here.
class Employer(models.Model):
  #Account Information
  user_name=models.CharField(max_length=20, default="", null = False)
  user_pass=models.CharField(max_length=12, default="", null = False)

  #Company Details
  company_name = models.CharField(max_length=200, default="", null = False)
  contact_person = models.CharField(max_length=200, default="", null = True)
  industry_type	= models.ManyToManyField("jobpost_app.Industry") #Foreign Key
  country = None
  city = None
  company_address = models.CharField(max_length=300, default="", null = False)
  billing_address = models.CharField(max_length=300, default="", null = False)
  contact_phone = models.CharField(max_length=13, default="", null = False)
  contact_email = models.CharField(max_length=100, default="", null = False)
  website = models.CharField(max_length=200, default="", null = True)

job_project/employer_app/models/job_post_model.py
from django.db import models


# Create your models here.
class JobPost(models.Model):
  #Account Information
  company = models.ForeignKey("employer_app.Employer", on_delete=models.CASCADE, null=True)
  category = models.ForeignKey("jobpost_app.Category", on_delete=models.CASCADE, null=True)
  industry = models.ForeignKey("jobpost_app.Industry", on_delete=models.CASCADE, null=True)
  job_title = models.CharField(max_length=200, default="", null=True)
  vacancies = models.IntegerField(default=1)
  with_photo = models.BooleanField(default=True)
  apply_ins = models.CharField(max_length=500, default="", null=True)
  last_date = models.DateTimeField(null=True)
  age_range_form = models.IntegerField(null=True)
  age_range_to = models.IntegerField(null=True)
  gender = models.IntegerField(null=True)
  job_type = models.IntegerField(null=True)
  job_level = models.IntegerField(null=True)
  edu_qualification = models.CharField(max_length=500, default="", null=True)
  job_context = models.CharField(max_length=500, default="", null=True)
  job_resp = models.CharField(max_length=500, default="", null=True)
  adtn_job_requirements = models.CharField(max_length=500, default="", null=True)
  adtn_job_req = models.CharField(max_length=500, default="", null=True)
  exp_type = models.IntegerField(null=True)
  exp_min = models.IntegerField(null=True)
  exp_max = models.IntegerField(null=True)
  location = models.ForeignKey("jobpost_app.Location", on_delete=models.CASCADE, null=True)
  salary_range_flag = models.IntegerField(null=True)
  salary_min = models.IntegerField(null=True)
  salary_max = models.IntegerField(null=True)
  other_benefits = models.CharField(max_length=500, default="", null=True)
  excl_job_flag = models.IntegerField(null=True)
  create_by = models.CharField(max_length=20, default="")
  create_date = models.DateTimeField(auto_now_add=True, null=True)
  update_by = models.CharField(max_length=20, default="")
  update_date = models.DateTimeField(auto_now=True, null=True)
  active = models.BooleanField(default=True)

job_project/employer_app/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    template = 'employer_app/emp_dashboard.html'
    context = {'title': 'Employer'}
    return render(request, template, context)

job_project/employer_app/views/employer_view.py
from django.shortcuts import render
from django.views import View
from employer_app import models as EmpModels
from jobpost_app import models as JobModels

# Create your views here.

class EmployerLoginReg(View):
    template='employer_app/employer_login_reg.html'
    def get(self, request, emp_id=None):
      return render(request, self.template, context={'title':'Employer Login/Registration'})

class EmployerCrud(View):

  template = 'employer_app/edit_employer_profile.html'
  industries = JobModels.Industry.objects.all()
  
  def get(self, request, emp_id=None):
    if emp_id:
      emp = EmpModels.Employer.objects.get(pk=1)
      context = {'title': 'Edit Employer Profile','emp':emp, 'industries':self.industries}
      return render(request, self.template, context)
    else:
      return render(request, self.template)
    
  def post(self, request, emp_id=None):
    #user_name =
    #user_pass =
    company_name = request.POST['com_name']
    #contact_person = request.POST['']
    industry_type = request.POST.getlist('industry_type')
    #country = 
    #city = 
    company_address = request.POST['com_address']
    billing_address = request.POST['billing_address']
    contact_phone = request.POST['contact_phone']
    contact_email = request.POST['contact_email']
    website = request.POST['website']
	
    industries =[]
    for ind_id in industry_type:
      inds=JobModels.Industry.objects.get(pk=ind_id)
      industries.append(inds)
		
	
	
    if emp_id:
      emp=EmpModels.Employer.objects.get(pk=emp_id)
      emp.company_name = company_name
      emp.company_address = company_address
      emp.billing_address = billing_address
      emp.contact_phone = contact_phone
      emp.contact_email = contact_email
      emp.website = website
      emp.industry_type = industries
      emp.save()
    else:
      emp=EmpModels.Employer(
        company_name = company_name,
	    company_address = company_address,
	    billing_address = billing_address,
	    contact_phone = contact_phone,
	    contact_email = contact_email,
	    website = website
	  )
      emp.save()
      emp.industry_type.add(*industries)
	  
    context={'title': 'Edit Employer Profile','emp':emp, 'industries':self.industries}
    return render(request, self.template, context)
	
	
	
	
	

job_project/employer_app/views/index_view.py
from django.shortcuts import render
from employer_app import models as JobPostModels

# Create your views here.
def index_view(request):
    template = 'employer_app/index.html'
    jobs = JobPostModels.JobPost.objects.all()
    context = {
      'title': 'Dashboard',
      'sub_title':'Application List',
      'jobs':jobs
	}
    return render(request, template, context)

job_project/employer_app/views/job_post_view.py
from django.shortcuts import render
from django.views import View
from employer_app import models as EmpModels
from jobpost_app import models as JobModels

# Create your views here.

class JobPostCrud(View):
    template = 'employer_app/job_post_form.html'
    industries = JobModels.Industry.objects.all()
    categories = JobModels.Category.objects.all()
    locations = JobModels.Location.objects.all()
    emp = EmpModels.Employer.objects.get(pk=1)
	
    def get(self, request, job_id=None):

      if job_id:
        jobpost = EmpModels.JobPost.objects.get(pk=job_id)
        context = {
          'title':'Create or Update Job Post',
          'emp':self.emp, 'industries':self.industries,
          'categories':self.categories,
          'locations':self.locations,
          'jobpost':jobpost
		}
        return render(request, self.template, context)
      else:
        context = {
          'title':'Create or Update Job Post',
          'emp':self.emp, 'industries':self.industries,
          'categories':self.categories,
          'locations':self.locations
		}
        return render(request, self.template, context)

    def post(self, request, job_id=None):
	  
      com_id = request.POST.get('com-id')
      category = request.POST.get('category')
      industry = request.POST.get('industry')
      job_title = request.POST.get('job-title','')
      vacancies = request.POST.get('vacancies','')
      attach_photo = request.POST.get('attach-photo','')
	  
      if job_id:
        jobpost = EmpModels.JobPost.objects.get(pk=job_id)
		
        jobpost.company_id = com_id
        jobpost.category_id = category
        jobpost.industry_id = industry
        jobpost.job_title = job_title
        jobpost.vacancies = vacancies
        jobpost.with_photo = attach_photo
        jobpost.save()
		
        context = {
          'title':'Create or Update Job Post',
          'emp':self.emp, 'industries':self.industries,
          'categories':self.categories,
          'locations':self.locations,
          'jobpost':jobpost,
		  'msg':'Job Updated!'
		}
        return render(request, self.template, context)
		
      else:
        jobpost=EmpModels.JobPost(
          company_id = com_id,
          category_id = category,
          industry_id = industry,
          job_title = job_title,
          vacancies = vacancies,
          with_photo = attach_photo
        )
        jobpost.save()
        context = {
          'title':'Create or Update Job Post',
          'emp':self.emp, 'industries':self.industries,
          'categories':self.categories,
          'locations':self.locations,
          'jobpost':jobpost,
		  'msg':'New Job Inserted!'
		}
        return render(request, self.template, context)

job_project/employer_app/templates/employer_app/edit_employer_profile.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">{{title}}</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="POST" action="{% url 'employer_app:upd-profile' 1 %}">
		{% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Company Name</label>
              <div class="col-md-7">
                <input type="text" name="com_name" value="{{emp.company_name}}" class="form-control" placeholder="Company Name">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Industry Type</label>
				 <div class="col-md-7">
				   <div class="row">
				      <div class="col-md-12">
				         <div class="row" style="height:120px;border:1px solid #ccc;margin:0;padding:0px ;overflow-y:auto;">
						 {% with inds_type=emp.industry_type.all %}
							{% for industry in industries %}
				            <div class="col-md-6">
				                <div class="checkbox">
				                  <label>
				                    <input type="checkbox" name="industry_type" value="{{industry.id}}"
									    {% for c in inds_type %}
											{% if c.id == industry.id %}
												checked
											{% endif %}
										{% endfor %}
									> {{industry.name}}
				                  </label>
				                </div>
				            </div>
							{% endfor %}
						 {% endwith %}
				        </div>
				        </div>
				    </div>
				</div>
            </div>
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Company Address</label>
              <div class="col-md-7">
                <input type="text" name="com_address" value="{{emp.company_address}}" class="form-control" placeholder="Company Address">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Billing Address</label>
              <div class="col-md-7">
                <input type="text" name="billing_address" value="{{emp.billing_address}}"  class="form-control" placeholder="Billing Address">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Contact Phone</label>
              <div class="col-md-7">
                <input type="text" name="contact_phone" value="{{emp.contact_phone}}" class="form-control" placeholder="88017XX XXX XXX">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Email</label>
              <div class="col-md-7">
                <input type="text" name="contact_email" value="{{emp.contact_email}}" class="form-control" placeholder="xxx@mail.com">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Website</label>
              <div class="col-md-7">
                <input type="text" name="website" value="{{emp.website}}" class="form-control" placeholder="http://www.xxx.com">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Chose Logo</label>
              <div class="col-md-7">
                <input type="file" id="exampleInputFile">
                <p class="help-block">
                	File must be in JPEG(.jpg or .jpeg) or GIF(.gif) or png format. 
					The height and width of the Applicant Photo must be equal(300x300). Max size 100KB
				</p>
              </div>
            </div>
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-default">Back</button>
            <button type="submit" class="btn btn-info pull-right">Update</button>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
  </div>
</div>
{% endblock content %}

job_project/employer_app/templates/employer_app/emp_dashboard.html
{% extends "admin_app/base.html" %}
{% load staticfiles %}
{% block dashboard %}
      

      <div class="row">
        <div class="col-md-12">
          <div class="box-body">
              <p>Add the classes <code>.btn.btn-app</code> to an <code>&lt;a&gt;</code> tag to achieve the following:</p>
              <a class="btn btn-app">
                <i class="fa fa-plus-square"></i> Post a Job
              </a>
              <a class="btn btn-app">
                <i class="fa fa-briefcase"></i> Company Jobs
              </a>
              <a class="btn btn-app">
                <i class="fa fa-edit"></i> Edit Profile
              </a>
              <a class="btn btn-app">
                <i class="fa fa-users"></i> Membership
              </a>
              <a class="btn btn-app">
                <i class="fa fa-power-off"></i> Log Out
              </a>
              <a class="btn btn-app">
                <i class="fa fa-exchange"></i> Change Password
              </a>
              <a class="btn btn-app">
                <i class="fa fa-trash"></i> Delete Account
              </a>
            </div>
        </div>
      </div>
{% endblock dashboard %}

job_project/employer_app/templates/employer_app/index.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">{{sub_title}}</h3>
        <div class="btn-group pull-right">
          <a href="{% url 'employer_app:job-post' '' %}" class="btn btn-primary btn-sm" role="button">Post a New Job</a>
          <a href="#" class="btn btn-info btn-sm" role="button">Search CV Bank</a>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body">
        <table class="table table-bordered">
          <tbody>
            <tr>
              <th style="width: 10px">SL</th>
              <th>Jobs Title</th>
              <th>Application</th>
              <th style="width:120px;text-align:center;">Action</th>
            </tr>
            {% for job in jobs %}
            <tr>
              <td>{{forloop.counter}}.</td>
              <td>{{job.job_title}}</td>
              <td>0</td>
              <td align="center">
                <div class="btn-group">
                  <a href="{% url 'employer_app:job-post' job.id %}" class="btn btn-warning btn-sm" role="button"><i class="fa fa-edit"></i></a>
                  <a href="#" class="btn btn-danger btn-sm" role="button"><i class="fa fa-trash"></i></a>
                </div>
              </td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- /.box-body -->
      <div class="box-footer clearfix">
        <ul class="pagination pagination-sm no-margin pull-right">
          <li><a href="#">«</a></li>
          <li><a href="#">1</a></li>
          <li><a href="#">2</a></li>
          <li><a href="#">3</a></li>
          <li><a href="#">»</a></li>
        </ul>
      </div>
    </div>
    <!-- /.box -->
  </div>
</div>
{% endblock content %}

job_project/employer_app/templates/employer_app/job_post_form.html
{% extends 'templates_app/backend/base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">{{msg}}</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form class="form-horizontal" method="POST" action="{% url 'employer_app:job-post' jobpost.id %}">
		{% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Company Name</label>
              <div class="col-md-7">
			    <input type="hidden" name="com-id" value="{{emp.id}}" class="form-control">
                <input type="text" name="com-name" value="{{emp.company_name}}" class="form-control" placeholder="Company Name" READONLY>
				
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Category</label>
      				<div class="col-md-7">
						<select name="category" class="form-control">
							<option vlaue="">--- Select Category ---</option>
							{% for category in categories %}
								<option value="{{category.id}}">{{category.name}}</option>
							{% endfor %}
						</select>
      				</div>
            </div>
			
			<div class="form-group">
              <label class="col-md-3 control-label">Industry Type</label>
				<div class="col-md-7">
					<select name="industry" class="form-control">
						<option vlaue="">--- Select Industry ---</option>
						{% for industry in industries %}
							<option value="{{industry.id}}">{{industry.name}}</option>
						{% endfor %}
					</select>
				</div>
            </div>
			
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Job Title</label>
              <div class="col-md-7">
                <input type="text" name="job-title" value="{{jobpost.job_title}}" class="form-control" placeholder="Job Title">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">No. of Vacancies</label>
              <div class="col-md-7">
                <input type="number" name="vacancies" value="{{jobpost.vacancies}}"  class="form-control" placeholder="No. of Vacancies">
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Applicant should enclose Photograph with CV ?</label>
              <div class="col-md-7">
                <label class="radio-inline">
                <input type="radio" name="attach-photo" value="1" checked=""> Yes</label>
                <label class="radio-inline">
                <input type="radio" name="attach-photo" value="0"> No</label>
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Apply Instruction(s)</label>
              <div class="col-md-7">
                  <textarea rows="4" cols="98" name="apply-ins" class="form-control" placeholder="Apply Instructions"></textarea>
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Apply Deadline</label>
              <div class="col-md-7">
                <input type="date" name="deadline" value="" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Age Range</label>
              <div class="col-md-3">
                  <div class="input-group">
                    <div class="input-group-addon">From</div>
                    <input type="number" name="age-frm" class="form-control">
                  </div>
              </div>
              <div class="col-md-3">
                  <div class="input-group">
                    <div class="input-group-addon">To</div>
                    <input type="number" name="age-to" class="form-control">
                  </div>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-3 control-label">Gender</label>
               <div class="col-md-7">
                    <select name="gender" class="form-control">
                      <option vlaue="">--- Select One ---</option>
                      <option value="1">Male</option>
                      <option value="2">Female</option>
                      <option value="3">Others</option>
                    </select>
              </div>
            </div>
			
            <div class="form-group">
              <label class="col-md-3 control-label">Job Type</label>
               <div class="col-md-7">
					<label class="checkbox-inline">
						<input name="job-type[]" value="1" type="checkbox"> Full Time
					</label>
					<label class="checkbox-inline">
						<input name="job-type[]" value="2" type="checkbox"> Part Time
					</label>
					<label class="checkbox-inline">
						<input name="job-type[]" value="3" type="checkbox"> Contractual
					</label>
					
					<label class="checkbox-inline">
						<input name="job-type[]" value="4" type="checkbox"> Internship
					</label>

              </div>
            </div>
			
            <div class="form-group">
              <label class="col-md-3 control-label">Job Level</label>
               <div class="col-md-7">
					<label class="checkbox-inline">
						<input name="job-level[]" value="1" type="checkbox"> Entry Level
					</label>
					<label class="checkbox-inline">
						<input name="job-level[]" value="2" type="checkbox"> Mid Level
					</label>
					<label class="checkbox-inline">
						<input name="job-level[]" value="3" type="checkbox"> Top Level
					</label>

              </div>
            </div>
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Educational Qualification</label>
              <div class="col-md-7">
                  <textarea rows="4" cols="98" name="edu-qlf" class="form-control" placeholder="Educational Qualification"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Job Context</label>
              <div class="col-md-7">
                  <textarea rows="4" cols="98" name="job-context" class="form-control" placeholder="Job Context"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Job Description/Responsibility</label>
              <div class="col-md-7">
                  <textarea rows="4" cols="98" name="job-resp" class="form-control" placeholder="Job Description/Responsibility"></textarea>
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Additional Job Requirements</label>
              <div class="col-md-7">
                  <textarea rows="4" cols="98" name="adn-req" class="form-control" placeholder="Additional Job Requirements"></textarea>
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label"></label>
              <div class="col-md-7">
                <label class="radio-inline">
                    <input name="experience_required" id="show-experience" value="1" type="radio">
                    Experience Required
                </label>
                <label class="radio-inline">
                    <input name="experience_required" id="no-experience" value="2" type="radio">
                    No Experience Required
                </label>
                <label class="radio-inline">
                    <input name="experience_required" id="exp-donot-mention" value="3" type="radio">
                    Do Not Mention
                </label>
              </div>
            </div>
            <div class="form-group">
              <label for="" class="col-md-3 control-label">Total Years of Experience</label>
              <div class="col-md-3">
                  <div class="input-group">
                    <div class="input-group-addon">Min</div>
                    <input type="number" name="min-exp" class="form-control">
                  </div>
              </div>
              <div class="col-md-3">
                  <div class="input-group">
                    <div class="input-group-addon">Max</div>
                    <input type="number" name="max-exp" class="form-control">
                  </div>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-3 control-label">Job Locations</label>
               <div class="col-md-7">
					<select name="location" class="form-control">
						<option vlaue="">--- Select Locations ---</option>
						{% for location in locations %}
							<option value="{{location.id}}">{{location.name}}</option>
						{% endfor %}
					</select>

              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Salary Range</label>
              <div class="col-md-7">
                <label class="radio-inline">
                    <input name="exp-req" value="1" checked="" type="radio">
                    Don't want to mention
                </label>
                <label class="radio-inline">
                    <input name="exp-req" value="2" type="radio">
                    Negotiable
                </label>
                <label class="radio-inline">
                    <input name="exp-req" value="3" type="radio">
                    Want to display the following range
                </label>
              </div>
            </div>
            
            <div class="form-group">
              <label for="" class="col-md-3 control-label"></label>
              <div class="col-md-3">
                  <div class="input-group">
                    <div class="input-group-addon">Min</div>
                    <input type="number" name="min-sal" class="form-control">
                  </div>
              </div>
              <div class="col-md-3">
                  <div class="input-group">
                    <div class="input-group-addon">Max</div>
                    <input type="number" name="max-sal" class="form-control">
                  </div>
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Other Benefits</label>
              <div class="col-md-7">
                  <textarea rows="4" cols="98" name="other-benifits" class="form-control" placeholder="Other Benefits"></textarea>
              </div>
            </div>

            <div class="form-group">
              <label for="" class="col-md-3 control-label">Request for 'Exclusive Job'</label>
              <div class="col-md-7">
                 <div class="checkbox">
                      <label>
                        <input type="checkbox" name="excl-job"> Yes
                      </label>
                    </div>
              </div>
            </div>
            
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <button type="submit" class="btn btn-default">Back</button>
            <button type="submit" class="btn btn-info pull-right">Post a New Job</button>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
  </div>
</div>
{% endblock content %}