job_project/admin_app/urls.py
from django.conf.urls import include, url
from . import views
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

job_project/employer_app/urls.py
from django.conf.urls import include, url
from employer_app.views.index_view import index_view
from employer_app.views.employer_view import EmployerCrud, EmployerLoginReg
from employer_app.views.job_post_view import JobPostCrud





urlpatterns = [
    url(r'^dashboard/$', index_view, name='dashboard'),
    url(r'^login/$', EmployerLoginReg.as_view(), name='emp-login'),
	url(r'^update-profile/(?P<emp_id>[0-9]*)$', EmployerCrud.as_view(), name='upd-profile'),
	url(r'^job-post/(?P<job_id>[0-9]*)$', JobPostCrud.as_view(), name='job-post'),
]

job_project/job_project/urls.py
from django.conf.urls import url, include
#from django.contrib import admin

urlpatterns = [
    url(r'^', include('jobpost_app.urls', namespace='jobpost_app')),
    url(r'^employer/', include('employer_app.urls', namespace='employer_app')),
    url(r'^seeker/', include('jobseeker_app.urls', namespace='seeker_app')),
    #url(r'^admin/', include('admin_app.urls')),
]

job_project/jobpost_app/urls.py
from django.conf.urls import include, url
from jobpost_app.views.index_view import (index_view)
from jobpost_app.views.backend_index_view import (backend_index_view)
from jobpost_app.views.backend_category_view import (backend_category_view, CategoryCrud)
from jobpost_app.views.backend_industry_view import (backend_industry_view, IndustryCrud)
from jobpost_app.views.backend_location_view import (backend_location_view, LocationCrud)

urlpatterns = [
	#Frontend Part
    url(r'^$', index_view, name='index'),
	
	#Backend Part
	url(r'^admin/dashboard/$', backend_index_view, name='backend_index'),
	url(r'^admin/category/$', backend_category_view, name='cat-list'),
	url(r'^admin/category-form/(?P<cat_id>[0-9]*)$', CategoryCrud.as_view(), name='cat-form'),
	url(r'^admin/industry/$', backend_industry_view, name='ind-list'),
	url(r'^admin/industry-form/(?P<ind_id>[0-9]*)$', IndustryCrud.as_view(), name='ind-form'),
	url(r'^admin/location/$', backend_location_view, name='job-loc'),
	url(r'^admin/location-form/(?P<loc_id>[0-9]*)$', LocationCrud.as_view(), name='loc-form'),
]

job_project/jobseeker_app/urls.py
from django.conf.urls import include, url
from jobseeker_app.views.seeker_index_view import seeker_index_view
from jobseeker_app.views.seeker_profile_view import SeekerLoginReg

urlpatterns = [
	url(r'^dashboard/$', seeker_index_view, name='dashboard'),
    url(r'^login/$', SeekerLoginReg.as_view(), name='seeker-login'),
]

job_project/jobpost_app/models/category.py
from django.db import models

# Create your models here.
class Category(models.Model):
  name = models.CharField(max_length=200, default="")
  slug = models.CharField(max_length=250, default="", unique=True)
  description = models.CharField(max_length=400, default="")
  create_by = models.CharField(max_length=20, default="")
  create_date = models.DateTimeField(auto_now_add=True, null=True)
  update_by = models.CharField(max_length=20, default="")
  update_date = models.DateTimeField(auto_now=True, null=True)
  active = models.BooleanField(default=True)

job_project/jobpost_app/models/industry.py
from django.db import models

# Create your models here.
class Industry(models.Model):
  name = models.CharField(max_length=200, default="")
  slug = models.CharField(max_length=250, default="", unique=True)
  description = models.CharField(max_length=400, default="")
  create_by = models.CharField(max_length=20, default="")
  create_date = models.DateTimeField(auto_now_add=True, null=True)
  update_by = models.CharField(max_length=20, default="")
  update_date = models.DateTimeField(auto_now=True, null=True)
  active = models.BooleanField(default=True)

job_project/jobpost_app/models/location.py
from django.db import models

# Create your models here.
class Location(models.Model):
  name = models.CharField(max_length=200, default="")
  slug = models.CharField(max_length=250, default="", unique=True)
  description = models.CharField(max_length=400, default="")
  create_by = models.CharField(max_length=20, default="")
  create_date = models.DateTimeField(auto_now_add=True, null=True)
  update_by = models.CharField(max_length=20, default="")
  update_date = models.DateTimeField(auto_now=True, null=True)
  active = models.BooleanField(default=True)

job_project/jobpost_app/views/backend_category_view.py
from django.shortcuts import render
from jobpost_app.models import Category
from django.views import View


# Create your views here.
def backend_category_view(request):
  template="jobpost_app/backend/category_list.html"
  cats=Category.objects.filter(active=True)
  context={'title':'Category List', 'cats':cats}
  return render(request, template, context)

class CategoryCrud(View):
  template="jobpost_app/backend/category_form.html"
  
  def get(self, request, cat_id=None):
    if cat_id:
      cat=Category.objects.get(pk=cat_id)
      context={'title':'Category Form', 'cat':cat}
      return render(request, self.template, context)
    else:
      return render(request, self.template, {'title':'Category Form'})
	
  def post(self, request, cat_id=None):
    name=request.POST.get('name','')
    slug=request.POST.get('slug','')
    desc=request.POST.get('description','')
    #status=request.POST.get('status','')
	
    if cat_id:
      cat=Category.objects.get(pk=cat_id)
      cat.name=name
      cat.slug=slug.lower()
      cat.description=desc
      #cat.active=status
      cat.save()
      msg='Data Updated Successfully'
    else:
      cat = Category(
        name = name,
        slug = slug.lower(),
        description = desc
        #active = status	  
	  )
      cat.save()
      msg='Data Inserted Successfully'
    context={'title':'Category Form', 'cat':cat, 'msg':msg}
    return render(request, self.template, context)

job_project/jobpost_app/views/backend_index_view.py
from django.shortcuts import render
from jobpost_app.models import Location


# Create your views here.
def backend_index_view(request):
  template="jobpost_app/backend/index.html"
  context={'title':'Jobpost Admin'}
  return render(request, template, context)

job_project/jobpost_app/views/backend_industry_view.py
from django.shortcuts import render
from jobpost_app.models import Industry
from django.views import View


# Create your views here.
def backend_industry_view(request):
  template="jobpost_app/backend/industry_list.html"
  inds=Industry.objects.filter(active=True)
  context={'title':'Industry List', 'inds':inds}
  return render(request, template, context)

class IndustryCrud(View):
  template="jobpost_app/backend/industry_form.html"
  
  def get(self, request, ind_id=None):
    if ind_id:
      ind=Industry.objects.get(pk=ind_id)
      context={'title':'Industry Form', 'ind':ind}
      return render(request, self.template, context)
    else:
      return render(request, self.template, {'title':'Industry Form'})
	
  def post(self, request, ind_id=None):
    name=request.POST.get('name','')
    slug=request.POST.get('slug','')
    desc=request.POST.get('description','')
    #status=request.POST.get('status','')
	
    if ind_id:
      ind=Industry.objects.get(pk=ind_id)
      ind.name=name
      ind.slug=slug.lower()
      ind.description=desc
      #ind.active=status
      ind.save()
      msg='Data Updated Successfully'
    else:
      ind = Industry(
        name = name,
        slug = slug.lower(),
        description = desc
        #active = status	  
	  )
      ind.save()
      msg='Data Inserted Successfully'
    context={'ind':ind, 'msg':msg}
    return render(request, self.template, context)

job_project/jobpost_app/views/backend_location_view.py
from django.shortcuts import render
from jobpost_app.models import Location
from django.views import View


# Create your views here.
def backend_location_view(request):
  template="jobpost_app/backend/location_list.html"
  locations=Location.objects.filter(active=True)
  context={'title':'Job Location List','locs':locations}
  return render(request, template, context)

  
class LocationCrud(View):
  template="jobpost_app/backend/location_form.html"
  
  def get(self, request, loc_id=None):
    if loc_id:
      loc=Location.objects.get(pk=loc_id)
      context={'title':'Job Location Form', 'loc':loc}
      return render(request, self.template, context)
    else:
      return render(request, self.template, {'title':'Job Location Form'})
	
  def post(self, request, loc_id=None):
    name=request.POST.get('name','')
    slug=request.POST.get('slug','')
    desc=request.POST.get('description','')
    #status=request.POST.get('status','')
	
    if loc_id:
      loc=Location.objects.get(pk=loc_id)
      loc.name=name
      loc.slug=slug.lower()
      loc.description=desc
      #loc.active=status
      loc.save()
      msg='Data Updated Successfully'
    else:
      loc = Location(
        name = name,
        slug = slug.lower(),
        description = desc
        #active = status	  
	  )
      loc.save()
      msg='Data Inserted Successfully'
    context={'title':'Job Location Form', 'loc':loc, 'msg':msg}
    return render(request, self.template, context)

job_project/jobpost_app/views/index_view.py
from django.shortcuts import render
from jobpost_app.models import Location, Category
#from django.http import HttpResponse


# Create your views here.
def index_view(request):
  template="jobpost_app/frontend/index.html"
  locs=Location.objects.all()
  cats=Category.objects.all()
  context={'title':'Welcome To My Jobs Site', 'locs':locs, 'cats':cats}
  return render(request, template, context)

job_project/jobpost_app/templates/jobpost_app/frontend/footer.html
{% load static %}
<div class="container-fluid" style="padding:20px 0px; background:#272626; color:#dddddd;">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<div style="text-align:left; padding: 60px 0px;">
					<img src="{% static 'frontend/img/logo.png' %}" height="40">
				</div>
			</div>
			
			<div class="col-md-2">
				<div class="footer">
					<h3>About Us</h3></br>
						<ul>
							<li><a href="#">About Jagojobs</a></li>
							<li><a href="#">Privacy  Policy</a></li>
							<li><a href="#">Contact Us</a></li>
						</ul>								
				</div>
			</div>
			
			<div class="col-md-2">
				<div class="footer">
					<h3>Joob Seeker</h3></br>
						<ul>
							<li><a href="{% url 'seeker_app:seeker-login' %}">Create Account</a></li>
							<li><a href="#">My Profile</a></li>
						</ul>								
				</div>
			</div>
			
			<div class="col-md-2">
				<div class="footer">
					<h3>Employers</h3></br>
						<ul>
							<li><a href="{% url 'employer_app:emp-login' %}">Create Account</a></li>
							<li><a href="#">Post a Job</a></li>
						</ul>								
				</div>
			</div>
			
			<div class="col-md-2">
				<div class="footer">
					<h3>Popular Jobs</h3></br>
						<ul>
							<li><a href="#">Gov. Jobs</a></li>
							<li><a href="#">Bank Jobs</a></li>
							<li><a href="#">NGO Jobs</a></li>
							<li><a href="#">Female Jobs</a></li>
						</ul>								
				</div>
			</div>

		</div>
	</div>
</div>
			
<div class="container-fluid" style="padding:20px;background:#1d1d1d;color:#dddddd;">
	<div class="container">
		<div class="row">
			<div class="col-md-10">All Rights Reserved. © Jagojobs.com 2017</div>
			<div class="col-md-2" style="text-align:right; ">
				<span class="glyphicon glyphicon-globe" aria-hidden="true"></span>&nbsp;&nbsp;
				<span class="glyphicon glyphicon-cloud" aria-hidden="true"></span>&nbsp;&nbsp;
				<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;&nbsp;
				<span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
			</div>
		</div>
	</div>
</div>

job_project/jobpost_app/templates/jobpost_app/frontend/joblist.html
{% extends 'templates_app/frontend/base.html' %}
{% load static %}
{% block title %}{{title}}{% endblock title %}

{% block parlax %}
	<!-- This div like a separator -->
	<div style="margin-top:100px; width:100%"></div> 
{% endblock parlax %}

{% block content %}

		<div class="panel panel-default">
			<div class="panel-heading fix">
				<div class="pull-left" style="margin:10px 0px; font-weight:bold;">
					Category : Accounts & Finance
				</div>
			</div>
			<div class="panel-body">
				<div class="media">
					<div class="media-left media-top">
						<a href="#">
						  <img class="media-object box-job-img" src="https://goo.gl/FvmZo6" alt="..." style="height:100px !important; weight:80px !important;">
						</a>
					</div>
					<div class="media-body">
						<div class="row">
							<div class="col-md-12"><h4 class="media-heading pull-left"><a href="#">Sr. Executive - Accounts</a></h4><span class="badge pull-right">Deadline : 21st Jul, 2017</span></div>
							<div class="col-md-12"><a href="#">Bestinbrands Private Limited</a></div>
						</div>
					
						<div class="row">
							<div class="col-md-2">Education<span class="pull-right">:</span></div>
							<div class="col-md-10">MBA/ M.Com/ CMA or ACCA...</div>
						</div>
					
						<div class="row">
							<div class="col-md-2">Experience<span class="pull-right">:</span></div>
							<div class="col-md-10">At least 5 year(s)</div>
						</div>
					</div>
				</div>
				
				<div class="media">
					<div class="media-left media-top">
						<a href="#">
						  <img class="media-object box-job-img" src="https://goo.gl/FvmZo6" alt="..." style="height:100px !important; weight:80px !important;">
						</a>
					</div>
					<div class="media-body">
						<div class="row">
							<div class="col-md-12"><h4 class="media-heading pull-left"><a href="#">Sr. Executive - Accounts</a></h4><span class="badge pull-right">Deadline : 21st Jul, 2017</span></div>
							<div class="col-md-12"><a href="#">Bestinbrands Private Limited</a></div>
						</div>
					
						<div class="row">
							<div class="col-md-2">Education<span class="pull-right">:</span></div>
							<div class="col-md-10">MBA/ M.Com/ CMA or ACCA...</div>
						</div>
					
						<div class="row">
							<div class="col-md-2">Experience<span class="pull-right">:</span></div>
							<div class="col-md-10">At least 5 year(s)</div>
						</div>
					</div>
				</div>
				
				<div class="media">
					<div class="media-left media-top">
						<a href="#">
						  <img class="media-object box-job-img" src="https://goo.gl/FvmZo6" alt="..." style="height:100px !important; weight:80px !important;">
						</a>
					</div>
					<div class="media-body">
						<div class="row">
							<div class="col-md-12"><h4 class="media-heading pull-left"><a href="#">Sr. Executive - Accounts</a></h4><span class="badge pull-right">Deadline : 21st Jul, 2017</span></div>
							<div class="col-md-12"><a href="#">Bestinbrands Private Limited</a></div>
						</div>
					
						<div class="row">
							<div class="col-md-2">Education<span class="pull-right">:</span></div>
							<div class="col-md-10">MBA/ M.Com/ CMA or ACCA...</div>
						</div>
					
						<div class="row">
							<div class="col-md-2">Experience<span class="pull-right">:</span></div>
							<div class="col-md-10">At least 5 year(s)</div>
						</div>
					</div>
				</div>
			</div>
			<div class="panel-footer fix">
				<div class="pull-right fix">
					<nav aria-label="Page navigation">
					  <ul class="pagination">
						<li>
						  <a href="#" aria-label="Previous">
							<span aria-hidden="true">&laquo;</span>
						  </a>
						</li>
						<li><a href="#">1</a></li>
						<li><a href="#">2</a></li>
						<li><a href="#">3</a></li>
						<li><a href="#">4</a></li>
						<li><a href="#">5</a></li>
						<li>
						  <a href="#" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
						  </a>
						</li>
					  </ul>
					</nav>
				</div>
			</div>
		</div>
{% endblock content %}


{% block sidebar %}
	<div class="fix" style="margin-bottom:10px;">
		<a href="#">
			<div class="category-list-icon">
				<div class="cat-jobs-icon pull-left MediumSeaGreen">
					<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
				</div>
				<span class="pull-left" style="margin: 4px 15px;">Account & Finance Jobs</span>
			</div>
		</a>
	</div>
	
	<div class="fix" style="margin-bottom:10px;">
		<a href="#">
			<div class="category-list-icon">
				<div class="cat-jobs-icon pull-left MediumPurple">
					<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
				</div>
				<span class="pull-left" style="margin: 4px 15px;">Driving & Motor Technician</span>
			</div>
		</a>
	</div>
	
	<div class="fix" style="margin-bottom:10px;">
		<a href="#">
			<div class="category-list-icon">
				<div class="cat-jobs-icon pull-left MediumOrchid">
					<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
				</div>
				<span class="pull-left" style="margin: 4px 15px;">NGO / Developments</span>
			</div>
		</a>
	</div>
	
	<div class="fix" style="margin-bottom:10px;">
		<a href="#">
			<div class="category-list-icon">
				<div class="cat-jobs-icon pull-left MediumBlue">
					<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
				</div>
				<span class="pull-left" style="margin: 4px 15px;">Account & Finance Jobs</span>
			</div>
		</a>
	</div>
	
	<div class="fix" style="margin-bottom:10px;">
		<a href="#">
			<div class="category-list-icon">
				<div class="cat-jobs-icon pull-left MediumAquaMarine">
					<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
				</div>
				<span class="pull-left" style="margin: 4px 15px;">Driving & Motor Technician</span>
			</div>
		</a>
	</div>
	
	<div class="fix" style="margin-bottom:10px;">
		<a href="#">
			<div class="category-list-icon">
				<div class="cat-jobs-icon pull-left YellowGreen">
					<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span>
				</div>
				<span class="pull-left" style="margin: 4px 15px;">NGO / Developments</span>
			</div>
		</a>
	</div>
{% endblock sidebar %}

job_project/jobpost_app/templates/jobpost_app/frontend/navbar.html
{% load static %}
<!-- Header Navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
	  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
	  </button>
	  <a class="navbar-brand" href="/"><img src="{% static 'frontend/img/logo.png' %}" height="20"></a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  <ul class="nav navbar-nav">
		<li><a href="/"><b>Home</b></a></li>
		<li class="dropdown">
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><b>Quick Link</b> <span class="caret"></span></a>
		  <ul class="dropdown-menu">
			<li><a href="#">Action</a></li>
			<li><a href="#">Another action</a></li>
			<li><a href="#">Something else here</a></li>
			<li role="separator" class="divider"></li>
			<li><a href="#">Separated link</a></li>
			<li role="separator" class="divider"></li>
			<li><a href="#">One more separated link</a></li>
		  </ul>
		</li>
	  </ul>
	  <form class="navbar-form navbar-right">
		<div class="form-group">
		  <input type="text" class="form-control" placeholder="Search your dream jobs ...">
		</div>
		<button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></button>
	  </form>
	  <ul class="nav navbar-nav navbar-right">
		<li><a href="{% url 'seeker_app:seeker-login' %}"><span class="glyphicon glyphicon-log-in"></span> <b>Seeker</b></a></li>
		<li><a href="{% url 'employer_app:emp-login' %}"><span class="glyphicon glyphicon-log-in"></span> <b>Employeer</b></a></li>
	  </ul>
	</div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

job_project/jobpost_app/templates/jobpost_app/frontend/seeker_login.html
{% extends './base.html' %}
{% load static %}

{% block title %}{{title}}{% endblock title %}

{% block parlax %}
	<!-- This div like a separator -->
	<div style="margin-top:100px; width:100%"></div> 
{% endblock parlax %}

{% block content %}
	<div style="min-height: 350px; padding:30px; margin: 0 0 30px 0; background: #ffffff; overflow: hidden;">
		<form>
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-6 form-group">
						<label>First Name</label>
						<input type="text" placeholder="Enter First Name Here.." class="form-control">
					</div>
					<div class="col-md-6 form-group">
						<label>Last Name</label>
						<input type="text" placeholder="Enter Last Name Here.." class="form-control">
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 form-group">
						<label>Email Address</label>
						<input type="text" placeholder="Enter Email Address Here.." class="form-control">
					</div>
					<div class="col-md-6 form-group">
						<label>Gender</label>
						<input type="text" placeholder="Enter Last Name Here.." class="form-control">
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 form-group">
						<label>Phone Number</label>
						<input type="text" placeholder="Enter Phone Number Here.." class="form-control">
					</div>
					<div class="col-md-6 form-group">
						<label>Jobs Category</label>
						<select class="form-control">
							{% for cat in cats %}
							<option value="{{cat.id}}">{{cat.name}}</option>
							{% endfor %}
					    </select>
					</div>
				</div>
				<hr>
				<div class="row">
					<div class="col-md-4 form-group">
						<label>User Name</label>
						<input type="text" placeholder="User Name" class="form-control">
					</div>
					<div class="col-md-4 form-group">
						<label>Password</label>
						<input type="password" placeholder="Password" class="form-control">
					</div>
					<div class="col-md-4 form-group">
						<label>Confirm Pass.</label>
						<input type="password" placeholder="Confirm Pass." class="form-control">
					</div>
				</div>	
				
			<button type="button" class="btn btn-info">Submit</button>					
			</div>
		</form>	
	</div>
{% endblock content %}


{% block sidebar %}
	<div class="all-jobs fix">
		<div class="all-jobs-icon pull-left">
			<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
		</div>
		<span class="pull-left" style="margin:10px;">Seeker Login</span>
	</div>
	<div style="padding:20px 10px; background: #ffffff;">
		<p style="font-size: 13px; text-align: center; width: 100%; padding: 3px; margin-bottom: :15px; border-bottom: 1px dotted #eee;">Already have an account? Please Login.</p>
		<form action="">
		  <div class="form-group">
		    <label for="exampleInputEmail1">Email address</label>
		    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Password</label>
		    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
		  </div>
		  <button type="submit" class="btn btn-primary">Login</button>
		  <br><br>
		  <a href="#" style="font-size: 12px; text-align: right;">Forgot Password? </a>
		</form>
	</div>
{% endblock sidebar %}